### ISSUE TITLE
Add support to math expressions (LaTex/MathJax support)

### ISSUE THREAD

**Issue by ClaraSantosmf** [ecarrara/obsidian-garden#8]
**Is your feature request related to a problem? Please describe.**
I use Obsidian to take note in class and then publish it online.

In my Database Course, there are many mathematical expressions in the subjects.
At first, we tried using regular characters to show math formulas, but that approach had some big limitations and was quite challenging to work with during classes, copying symbols from the internet. Like Ȼ e 3√y.

As the next step, we started using [Quick LaTeX Obsidian](https://github.com/joeyuping/quick_latex_obsidian) to write mathematical expressions, and it's been a very good solution! However, we encountered difficulties converting LaTeX expressions to Markdown and publishing them accurately..

**Describe the solution you'd like**
Add support to [math syntax like Obsidian does](https://help.obsidian.md/Editing+and+formatting/Advanced+formatting+syntax#Math).

Using double dollar signs:
```
$$
\begin{vmatrix}a & b\\
c & d
\end{vmatrix}=ad-bc
$$
```
And inline math expression using single dollar, like `$e^{2i\pi} = 1$.`

**Additional context**
A online example [here](https://clarasantosmf.github.io/FATEC/FATEC/1%C2%BA%20Semestre%20(2023.2)/MMD001%20-%20Matem%C3%A1tica%20discreta/2023-08-18%20(2%C2%AA%20aula)%20B%C3%A1sico%20de%20conjunto%20e%20l%C3%B3gica.html).

**Comment by ecarrara** [comment]
Closed in #9
